# Generated by Django 3.0.2 on 2020-01-25 21:29

from django.db import migrations, models
import django.db.models.deletion
import kcevent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KCEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KCEventPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evp_doc_contract', models.FileField(upload_to=kcevent.models.getUploadPathEventPartnerContract)),
                ('evp_apx_participant_m', models.PositiveSmallIntegerField()),
                ('evp_apx_participant_w', models.PositiveSmallIntegerField()),
                ('evp_apx_reloaded_m', models.PositiveSmallIntegerField()),
                ('evp_apx_reloaded_w', models.PositiveSmallIntegerField()),
                ('evp_apx_member_m', models.PositiveSmallIntegerField()),
                ('evp_apx_member_w', models.PositiveSmallIntegerField()),
                ('evp_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.KCEvent')),
            ],
        ),
        migrations.CreateModel(
            name='KCPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('house_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('mail_addr', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=120)),
                ('house_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=10)),
                ('mail_church', models.EmailField(max_length=254)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson')),
                ('events', models.ManyToManyField(through='kcevent.KCEventPartner', to='kcevent.KCEvent')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson')),
            ],
        ),
        migrations.AddField(
            model_name='kceventpartner',
            name='evp_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.Partner'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('kcperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kcevent.KCPerson')),
                ('birthday', models.DateField()),
                ('intolerances', models.TextField()),
                ('nutrition', models.CharField(choices=[('RGL', 'Regulär'), ('VGT', 'Vegetarisch'), ('VGN', 'Vegan')], default='RGL', max_length=3)),
                ('role', models.CharField(choices=[('CF', 'Konfirmand'), ('RL', 'Reloaded'), ('ST', 'Mitarbeiter')], default='CF', max_length=2)),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kcevent.Partner')),
            ],
            bases=('kcevent.kcperson',),
        ),
        migrations.CreateModel(
            name='KCEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField()),
                ('reg_doc_pass', models.FileField(upload_to=kcevent.models.getUploadPathEventRegistration)),
                ('reg_doc_meddispense', models.FileField(upload_to=kcevent.models.getUploadPathEventRegistration)),
                ('reg_doc_consent', models.FileField(upload_to=kcevent.models.getUploadPathEventRegistration)),
                ('reg_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.KCEvent')),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='kcevent',
            name='participants',
            field=models.ManyToManyField(through='kcevent.KCEventRegistration', to='kcevent.Participant'),
        ),
    ]
