# Generated by Django 3.0.2 on 2020-01-27 19:48

from django.db import migrations, models
import kcevent.models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0002_auto_20200126_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kcevent',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='kceventpartner',
            options={'verbose_name': 'Event Partner', 'verbose_name_plural': 'Event Partners'},
        ),
        migrations.AlterModelOptions(
            name='kceventregistration',
            options={'verbose_name': 'Event registration', 'verbose_name_plural': 'Event registrations'},
        ),
        migrations.AlterModelOptions(
            name='kcperson',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partner'},
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('D', 'Divert')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_member_m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_member_w',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_participant_m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_participant_w',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_reloaded_m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_reloaded_w',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_meddispense',
            field=models.FileField(blank=True, null=True, upload_to=kcevent.models.getUploadPathEventRegistration),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='intolerances',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nutrition',
            field=models.CharField(choices=[('RGL', 'Regular'), ('VGT', 'Vegetarian'), ('VGN', 'Vegan')], default='RGL', max_length=3),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('CF', 'Confirmand'), ('RL', 'Reloaded'), ('ST', 'Staff')], default='CF', max_length=2),
        ),
    ]
