# Generated by Django 3.0.2 on 2020-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0003_auto_20200127_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('D', 'Divert')], max_length=1),
        ),
    ]
