# Generated by Django 3.0.2 on 2020-01-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0004_auto_20200127_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nutrition',
            field=models.CharField(choices=[('RGL', 'Regular'), ('VGT', 'Vegetarian'), ('VGN', 'Vegan')], max_length=3),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('CF', 'Confirmand'), ('RL', 'Reloaded'), ('ST', 'Staff')], max_length=2),
        ),
    ]
