# Generated by Django 3.0.2 on 2020-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0005_auto_20200127_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='kceventregistration',
            name='reg_notes',
            field=models.TextField(blank=True),
        ),
    ]
