# Generated by Django 3.0.2 on 2020-01-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0007_auto_20200127_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcevent',
            name='event_url',
            field=models.SlugField(default='kc2020'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kcevent',
            name='registrationPassword',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
