# Generated by Django 3.0.2 on 2020-01-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0008_auto_20200128_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kcevent',
            old_name='registrationPassword',
            new_name='reg_pwd',
        ),
    ]
