# Generated by Django 3.0.2 on 2020-01-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0009_auto_20200128_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='celiac_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='lactose_intolerance',
            field=models.BooleanField(default=False),
        ),
    ]
