# Generated by Django 3.0.2 on 2020-01-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0010_auto_20200130_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcevent',
            name='registration_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kcevent',
            name='registration_start',
            field=models.DateField(null=True),
        ),
    ]
