# Generated by Django 3.0.2 on 2020-02-02 12:11

from django.db import migrations, models
import django.db.models.deletion
import kcevent.models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0011_auto_20200130_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcevent',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson', verbose_name='Organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kceventregistration',
            name='confirmation_dt',
            field=models.DateTimeField(null=True, verbose_name='Confirmation date/time'),
        ),
        migrations.AddField(
            model_name='kceventregistration',
            name='confirmation_send',
            field=models.BooleanField(default=False, verbose_name='Confirmation send'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='event_url',
            field=models.SlugField(help_text='SEO optimized location for register to event.', verbose_name='Registration URL'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='participants',
            field=models.ManyToManyField(through='kcevent.KCEventRegistration', to='kcevent.Participant', verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='reg_pwd',
            field=models.CharField(blank=True, help_text='Password (can be empty) which is necessary in order to be able to register to event.', max_length=250, verbose_name='Registration password'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='registration_end',
            field=models.DateField(null=True, verbose_name='Registration end'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='registration_start',
            field=models.DateField(null=True, verbose_name='Registration start'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_member_m',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approx. no. of male members'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_member_w',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approx. no. of female members'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_participant_m',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approx. no. of male par.'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_participant_w',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approx. no. of female par.'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_reloaded_m',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approx. no. of male reloaded'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_apx_reloaded_w',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Approx. no. of female reloaded'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_doc_contract',
            field=models.FileField(null=True, upload_to=kcevent.models.getUploadPathEventPartner, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.KCEvent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='kceventpartner',
            name='evp_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.Partner', verbose_name='Event partner'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_consent',
            field=models.FileField(upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Consent form'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_meddispense',
            field=models.FileField(blank=True, null=True, upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Medical dispense'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_pass',
            field=models.FileField(upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Event passport'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.KCEvent', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration time'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.Participant', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='city',
            field=models.CharField(max_length=120, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='House no.'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='mail_addr',
            field=models.EmailField(max_length=254, verbose_name='Mail address'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='street',
            field=models.CharField(max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='kcperson',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='celiac_disease',
            field=models.BooleanField(default=False, verbose_name='Celiac disease'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='church',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kcevent.Partner', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Female'), ('D', 'Divert')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='intolerances',
            field=models.TextField(blank=True, verbose_name='Intolerances'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lactose_intolerance',
            field=models.BooleanField(default=False, verbose_name='Lactose intolerance'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('CF', 'Confirmand'), ('RL', 'Reloaded'), ('ST', 'Staff')], max_length=2, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(max_length=120, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson', verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='events',
            field=models.ManyToManyField(through='kcevent.KCEventPartner', to='kcevent.KCEvent', verbose_name='Events'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='House no.'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='mail_church',
            field=models.EmailField(max_length=254, verbose_name='Mail address'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson', verbose_name='Responsible person'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='street',
            field=models.CharField(max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Postal code'),
        ),
    ]
