# Generated by Django 3.0.2 on 2020-02-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0012_auto_20200202_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kceventpartner',
            options={'verbose_name': 'Event partner', 'verbose_name_plural': 'Event partners'},
        ),
        migrations.RemoveField(
            model_name='kcevent',
            name='organizer',
        ),
        migrations.CreateModel(
            name='KCEventHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('house_number', models.CharField(max_length=10, verbose_name='House no.')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('mail_addr', models.EmailField(max_length=254, verbose_name='Mail address')),
                ('website', models.URLField(verbose_name='Website')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson', verbose_name='Contact person')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCPerson', verbose_name='Responsible person')),
            ],
            options={
                'verbose_name': 'Event host',
                'verbose_name_plural': 'Event hosts',
            },
        ),
        migrations.AddField(
            model_name='kcevent',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kcevent.KCEventHost', verbose_name='Host'),
            preserve_default=False,
        ),
    ]
