# Generated by Django 3.0.2 on 2020-02-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0013_auto_20200202_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventhost',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
