# Generated by Django 3.0.2 on 2020-02-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0015_auto_20200202_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCTemplateSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Template set',
                'verbose_name_plural': 'Template sets',
            },
        ),
        migrations.AddField(
            model_name='kcevent',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kcevent.KCTemplateSet', verbose_name='Template set'),
        ),
        migrations.CreateModel(
            name='KCTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpl_type', models.CharField(choices=[('registrationConfirmation', 'Confirm registration to participant')], max_length=50, verbose_name='Template type')),
                ('tpl_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kcevent.KCTemplateSet', verbose_name='Template set')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'unique_together': {('tpl_set', 'tpl_type')},
            },
        ),
    ]
