# Generated by Django 3.0.2 on 2020-02-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0016_auto_20200202_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='kctemplate',
            name='tpl_content',
            field=models.TextField(null=True, verbose_name='Body template'),
        ),
        migrations.AddField(
            model_name='kctemplate',
            name='tpl_subject',
            field=models.CharField(max_length=255, null=True, verbose_name='Subject template'),
        ),
        migrations.AlterField(
            model_name='kcevent',
            name='template',
            field=models.ForeignKey(help_text='A set of templates used in order to send mails.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kcevent.KCTemplateSet', verbose_name='Template set'),
        ),
    ]
