# Generated by Django 3.0.2 on 2020-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0018_auto_20200202_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='mail_church',
            new_name='mail_addr',
        ),
        migrations.AlterField(
            model_name='kctemplate',
            name='tpl_type',
            field=models.CharField(choices=[('registrationConfirmation', 'Confirm registration to participant'), ('registrationNotification', 'Confirm registration to church and host')], max_length=50, verbose_name='Template type'),
        ),
    ]
