# Generated by Django 3.0.2 on 2020-02-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0019_auto_20200202_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kctemplate',
            name='tpl_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.KCTemplateSet', verbose_name='Template set'),
        ),
    ]
