# Generated by Django 3.0.2 on 2020-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0020_auto_20200202_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='kceventregistration',
            name='reg_consent',
            field=models.BooleanField(default=False, verbose_name='Consent parents'),
        ),
    ]
