# Generated by Django 3.0.2 on 2020-02-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0021_kceventregistration_reg_consent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kceventregistration',
            options={'permissions': (('can_download_regdocs', 'Can download registration documents'),), 'verbose_name': 'Event registration', 'verbose_name_plural': 'Event registrations'},
        ),
    ]
