# Generated by Django 3.0.4 on 2021-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0022_auto_20200229_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kctemplate',
            name='tpl_type',
            field=models.CharField(choices=[('registrationConfirmation', 'Confirm registration to participant'), ('registrationNotification', 'Confirm registration to church and host'), ('formIntroduction', 'Introduction to event')], max_length=50, verbose_name='Template type'),
        ),
    ]
