# Generated by Django 3.0.4 on 2021-02-20 11:57

from django.db import migrations, models
import kcevent.models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0022_auto_20200229_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcevent',
            name='onSiteAttendance',
            field=models.BooleanField(default=True, help_text='In case event is an on-site attendance event, futher documents are requested by the participant during registration.', verbose_name='On-site attendance'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_pass',
            field=models.FileField(blank=True, null=True, upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Event passport'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='celiac_disease',
            field=models.BooleanField(null=True, verbose_name='Celiac disease'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='intolerances',
            field=models.TextField(null=True, verbose_name='Intolerances'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lactose_intolerance',
            field=models.BooleanField(null=True, verbose_name='Lactose intolerance'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nutrition',
            field=models.CharField(choices=[('RGL', 'Regular'), ('VGT', 'Vegetarian'), ('VGN', 'Vegan')], max_length=3, null=True),
        ),
    ]
