# Generated by Django 3.0.4 on 2021-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0023_auto_20210220_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kctemplate',
            name='tpl_type',
            field=models.CharField(choices=[('registrationConfirmation', 'Confirm registration to participant'), ('registrationNotification', 'Confirm registration to church and host'), ('formLogin', 'Notes during login to event'), ('formIntroduction', 'Introduction to event')], max_length=50, verbose_name='Template type'),
        ),
    ]
