# Generated by Django 3.0.4 on 2021-02-20 12:02

from django.db import migrations, models
import kcevent.models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0023_auto_20210220_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_consent',
            field=models.FileField(null=True, upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Consent form'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_meddispense',
            field=models.FileField(null=True, upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Medical dispense'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_pass',
            field=models.FileField(null=True, upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Event passport'),
        ),
    ]
