# Generated by Django 3.0.4 on 2021-02-20 12:18

from django.db import migrations, models
import kcevent.models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0026_auto_20210220_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_consent',
            field=models.FileField(blank=True, default=' ', upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Consent form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_meddispense',
            field=models.FileField(blank=True, default=' ', upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Medical dispense'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_doc_pass',
            field=models.FileField(blank=True, default=' ', upload_to=kcevent.models.getUploadPathEventRegistration, verbose_name='Event passport'),
            preserve_default=False,
        ),
    ]
