# Generated by Django 3.0.4 on 2021-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0027_auto_20210220_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_consent',
            field=models.BooleanField(verbose_name='Consent parents'),
        ),
    ]
