# Generated by Django 3.0.4 on 2021-02-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0028_auto_20210220_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventregistration',
            name='reg_consent',
            field=models.BooleanField(default=False, verbose_name='Consent parents'),
        ),
    ]
