# Generated by Django 3.0.2 on 2021-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0024_auto_20210220_1050'),
        ('kcevent', '0029_auto_20210220_1225'),
    ]

    operations = [
    ]
