# Generated by Django 3.0.2 on 2021-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0030_merge_20210225_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcevent',
            name='onSiteAttendance',
            field=models.BooleanField(default=True, help_text='In case event is an on-site attendance event, further documents are requested by the participant during registration.', verbose_name='On-site attendance'),
        ),
    ]
