# Generated by Django 5.0.4 on 2024-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0035_kceventregistration_confirmation_partner_dt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kceventregistration",
            name="confirmation_partner_dt",
            field=models.DateTimeField(
                null=True, verbose_name="Partner confirmation date/time"
            ),
        ),
        migrations.AlterField(
            model_name="kceventregistration",
            name="confirmation_partner_send",
            field=models.BooleanField(
                default=False, verbose_name="Partner confirmation send"
            ),
        ),
    ]
