# Generated by Django 5.0 on 2023-12-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0035_kceventregistration_confirmation_partner_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventregistration',
            name='confirmation_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation date/time'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='confirmation_partner_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Partner confirmation date/time'),
        ),
        migrations.AlterField(
            model_name='kceventregistration',
            name='confirmation_partner_send',
            field=models.BooleanField(default=False, verbose_name='Partner confirmation send'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[(None, 'Please choose your gender'), ('M', 'Male'), ('W', 'Female'), ('D', 'Divert')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nutrition',
            field=models.CharField(blank=True, choices=[(None, 'Please choose your nutrition'), ('RGL', 'Regular'), ('VGT', 'Vegetarian'), ('VGN', 'Vegan')], default='', max_length=3, verbose_name='Nutrition'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[(None, 'Please choose your role'), ('CF', 'Confirmand'), ('RL', 'Reloaded'), ('ST', 'Staff')], max_length=2, verbose_name='Role'),
        ),
    ]
