# Generated by Django 5.0 on 2023-12-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0036_alter_kceventregistration_confirmation_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCEventDailyParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(verbose_name='Event day')),
                ('participation_type', models.CharField(choices=[(None, 'No participation'), ('day', 'Day guest'), ('night', 'Overnight'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('sick', 'Sick')], max_length=20, verbose_name='Type of participation')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcevent.kceventregistration', verbose_name='Event registration')),
            ],
            options={
                'verbose_name': 'Event daily participant',
                'verbose_name_plural': 'Event daily participants',
            },
        ),
    ]
