# Generated by Django 5.0.4 on 2024-04-17 19:13

import kcevent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0036_alter_kceventregistration_confirmation_partner_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kceventregistration",
            name="reg_status",
            field=models.CharField(
                choices=[
                    (None, "Please choose status of registration"),
                    ("registered", "Registered"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined"),
                ],
                default="registered",
                max_length=20,
                verbose_name="Registration status",
            ),
        ),
        migrations.AlterField(
            model_name="kceventpartner",
            name="evp_doc_contract",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kcevent.models.getUploadPathEventPartnerContract,
                verbose_name="Contract",
            ),
        ),
    ]
