# Generated by Django 5.0 on 2023-12-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0037_kceventdailyparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kceventdailyparticipant',
            name='participation_type',
            field=models.CharField(choices=[(None, 'Please choose type of participation'), ('no', 'No participation'), ('day', 'Day guest'), ('night', 'Overnight'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('sick', 'Sick')], max_length=20, verbose_name='Type of participation'),
        ),
    ]
