# Generated by Django 5.0.4 on 2024-04-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0036_alter_kceventregistration_confirmation_dt_and_more"),
        ("kcevent", "0037_kceventregistration_reg_status_and_more"),
    ]

    operations = []
