# Generated by Django 5.0 on 2023-12-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0038_alter_kceventdailyparticipant_participation_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kceventdailyparticipant',
            unique_together={('registration', 'day')},
        ),
    ]
