# Generated by Django 5.0 on 2023-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcevent', '0039_alter_kceventdailyparticipant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='kceventregistration',
            name='reg_status',
            field=models.CharField(choices=[(None, 'Please choose status of registration'), ('registered', 'Registered'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='registered', max_length=20, verbose_name='Registration status'),
        ),
    ]
