# Generated by Django 5.0.4 on 2024-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0039_kceventexportsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
