# Generated by Django 5.1 on 2024-08-31 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0041_kcevent_partners_alter_kcevent_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="kcevent",
            name="display_event_info",
            field=models.BooleanField(
                default=True,
                help_text="Display event meta information on registration page for better recognizing the reason for registration.",
                verbose_name="Display event info",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kcevent.partner",
                verbose_name="Partner",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="nutrition",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Please choose your nutrition"),
                    ("RGL", "Meat-based diet"),
                    ("VGT", "Vegetarian diet"),
                    ("VGN", "Vegan diet"),
                ],
                default="",
                max_length=3,
                verbose_name="Nutrition",
            ),
        ),
    ]
