# Generated by Django 5.1 on 2024-08-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kcevent",
            "0042_kcevent_display_event_info_alter_participant_church_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="KCEventLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Address line 2"
                    ),
                ),
                (
                    "address_line_3",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Address line 3"
                    ),
                ),
                ("street", models.CharField(max_length=120, verbose_name="Street")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="House no."),
                ),
                ("city", models.CharField(max_length=120, verbose_name="City")),
                (
                    "zip_code",
                    models.CharField(max_length=10, verbose_name="Postal code"),
                ),
                (
                    "mail_addr",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Mail address"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
            ],
            options={
                "verbose_name": "Event location",
                "verbose_name_plural": "Event locations",
            },
        ),
        migrations.AddField(
            model_name="kceventhost",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Address line 2"
            ),
        ),
        migrations.AddField(
            model_name="kceventhost",
            name="address_line_3",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Address line 3"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="address_line_2",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Address line 2"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="address_line_3",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Address line 3"
            ),
        ),
        migrations.AddField(
            model_name="kcevent",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="kcevent.kceventlocation",
                verbose_name="Event location",
            ),
        ),
    ]
