# Generated by Django 5.1 on 2024-09-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0044_kceventpartner_evp_apx_member_d_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kceventregistration",
            name="reg_consent_privacy",
            field=models.BooleanField(default=False, verbose_name="Consent privacy"),
        ),
        migrations.AlterField(
            model_name="kctemplate",
            name="tpl_type",
            field=models.CharField(
                choices=[
                    ("registrationConfirmation", "Confirm registration to participant"),
                    (
                        "registrationNotification",
                        "Confirm registration to church and host",
                    ),
                    ("formLogin", "Notes during login to event"),
                    ("formIntroduction", "Introduction to event"),
                    (
                        "formStatementOverview",
                        "Statement on registration confirmation page",
                    ),
                ],
                max_length=50,
                verbose_name="Template type",
            ),
        ),
    ]
