# Generated by Django 5.1 on 2024-09-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0045_kceventregistration_reg_consent_privacy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KCEventPriceRule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "currency",
                    models.CharField(
                        default="€", max_length=100, verbose_name="Currency"
                    ),
                ),
                ("price", models.FloatField(default=0.0, verbose_name="Price")),
                (
                    "members_only",
                    models.BooleanField(default=False, verbose_name="For members only"),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(default=0, verbose_name="Minimum age"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kcevent.kcevent",
                        verbose_name="Event",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kcevent.partner",
                        verbose_name="Event partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price rule",
                "verbose_name_plural": "Price rules",
            },
        ),
    ]
