# Generated by Django 5.1 on 2024-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0046_kceventpricerule"),
    ]

    operations = [
        migrations.AddField(
            model_name="kceventpricerule",
            name="role",
            field=models.CharField(
                choices=[
                    (None, "Please choose your role"),
                    ("CF", "Confirmand"),
                    ("RL", "Reloaded"),
                    ("ST", "Staff"),
                ],
                default=None,
                max_length=2,
                null=True,
                verbose_name="Role",
            ),
        ),
    ]
