# Generated by Django 5.1 on 2024-09-01 08:14

import django.db.models.deletion
import kcevent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0048_alter_kceventpricerule_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="kceventpartner",
            name="evp_doc_policy",
            field=models.FileField(
                blank=True,
                help_text="This field allows to upload a document for General Terms and Conditions to be agreed by participants.",
                null=True,
                upload_to=kcevent.models.getUploadPathEventPartnerGTAC,
                verbose_name="General Terms and Conditions",
            ),
        ),
        migrations.AlterField(
            model_name="kceventpricerule",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kcevent.partner",
                verbose_name="Event partner",
            ),
        ),
    ]
