# Generated by Django 5.1 on 2024-09-01 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0049_kceventpartner_evp_doc_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kcevent",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="kceventpartner",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
