# Generated by Django 5.1 on 2024-09-01 08:27

from django.db import migrations
import uuid


def gen_uuid_kcevent(apps, schema_editor):
    KCEvent = apps.get_model("kcevent", "KCEvent")
    for row in KCEvent.objects.all():
        row.ext_id = uuid.uuid4()
        row.save(update_fields=["ext_id"])

def gen_uuid_kceventpartner(apps, schema_editor):
    KCEventPartner = apps.get_model("kcevent", "KCEventPartner")
    for row in KCEventPartner.objects.all():
        row.ext_id = uuid.uuid4()
        row.save(update_fields=["ext_id"])

def gen_uuid_partner(apps, schema_editor):
    Partner = apps.get_model("kcevent", "Partner")
    for row in Partner.objects.all():
        row.ext_id = uuid.uuid4()
        row.save(update_fields=["ext_id"])

class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0050_kcevent_ext_id_kceventpartner_ext_id_partner_ext_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid_kcevent, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid_kceventpartner, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid_partner, reverse_code=migrations.RunPython.noop),
    ]
