# Generated by Django 5.1 on 2024-09-01 08:31

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0051_assign_unique_extid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kcevent",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="kceventpartner",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="partner",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
