# Generated by Django 5.1 on 2024-09-01 08:35

import kcevent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0052_make_extid_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kceventpartner",
            name="evp_doc_contract",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=kcevent.models.getUploadPathEventPartnerContract,
                verbose_name="Contract",
            ),
        ),
        migrations.AlterField(
            model_name="kceventpartner",
            name="evp_doc_policy",
            field=models.FileField(
                blank=True,
                help_text="This field allows to upload a document for General Terms and Conditions to be agreed by participants.",
                max_length=255,
                null=True,
                upload_to=kcevent.models.getUploadPathEventPartnerGTAC,
                verbose_name="General Terms and Conditions",
            ),
        ),
    ]
