# Generated by Django 5.2 on 2025-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0057_kcevent_enableprices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kcevent",
            name="participants",
            field=models.ManyToManyField(
                through="kcevent.KCEventRegistration",
                through_fields=("reg_event", "reg_user"),
                to="kcevent.participant",
                verbose_name="Participants",
            ),
        ),
        migrations.AlterField(
            model_name="kcevent",
            name="partners",
            field=models.ManyToManyField(
                through="kcevent.KCEventPartner",
                through_fields=("evp_event", "evp_partner"),
                to="kcevent.partner",
                verbose_name="Partners",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="events",
            field=models.ManyToManyField(
                through="kcevent.KCEventRegistration",
                through_fields=("reg_user", "reg_event"),
                to="kcevent.kcevent",
                verbose_name="Events",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="events",
            field=models.ManyToManyField(
                through="kcevent.KCEventPartner",
                through_fields=("evp_partner", "evp_event"),
                to="kcevent.kcevent",
                verbose_name="Events",
            ),
        ),
    ]
