# Generated by Django 5.2 on 2025-04-27 09:04

import uuid
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    KCEventRegistration = apps.get_model('kcevent', 'KCEventRegistration')
    for reg in KCEventRegistration.objects.all():
        reg.ext_id = uuid.uuid4()
        reg.save()


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0058_alter_kcevent_participants_alter_kcevent_partners_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kceventregistration",
            name="ext_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="kceventregistration",
            name="ext_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False, blank=False),
        ),
    ]
