# Generated by Django 5.2 on 2025-06-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0059_kceventregistration_ext_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="kcevent",
            name="enableEmergencyContacts",
            field=models.BooleanField(
                default=False,
                help_text="Ask and require certain forms and documents from user to upload.",
                verbose_name="Ask for emergency contacts",
            ),
        ),
        migrations.CreateModel(
            name="KCEmergencyContact",
            fields=[
                (
                    "kcperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kcevent.kcperson",
                    ),
                ),
                (
                    "role",
                    models.TextField(blank=True, verbose_name="Emergency contact role"),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kcevent.kceventregistration",
                        verbose_name="Registrierung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency contacts",
                "verbose_name_plural": "Emergency contacts",
            },
            bases=("kcevent.kcperson",),
        ),
    ]
