# Generated by Django 5.2 on 2025-06-30 07:22

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0062_kcevent_regform_schema_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kceventregistration",
            name="reg_adddata",
            field=django_jsonform.models.fields.JSONField(
                default=dict, verbose_name="Additional form data"
            ),
        ),
    ]
