# Generated by Django 5.2 on 2025-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0063_kceventregistration_reg_adddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="kcevent",
            name="notify_sender_address",
            field=models.EmailField(
                blank=True,
                help_text="Override the systems default sender address for notifications.",
                max_length=254,
                verbose_name="Notification sender address",
            ),
        ),
    ]
