# Generated by Django 5.2 on 2025-06-30 10:37

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0064_kcevent_notify_sender_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kceventregistration",
            name="reg_adddata",
            field=django_jsonform.models.fields.JSONField(
                blank=True, default=dict, verbose_name="Additional form data"
            ),
        ),
    ]
