# Generated by Django 5.2 on 2025-07-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0065_alter_kceventregistration_reg_adddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="KCEventPartnerRoleStatistic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            (None, "Please choose your gender"),
                            ("M", "Male"),
                            ("W", "Female"),
                            ("D", "Divert"),
                        ],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "apx_participants",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Approx. no. of par."
                    ),
                ),
                (
                    "event_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kcevent.kceventpartner",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kcevent.participantrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Role Statistic",
                "verbose_name_plural": "Partner Role Statistics",
                "unique_together": {("role", "event_partner")},
            },
        ),
    ]
