# Generated by Django 5.2 on 2025-07-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0066_kceventpartnerrolestatistic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_member_d",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_member_m",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_member_w",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_participant_d",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_participant_m",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_participant_w",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_reloaded_d",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_reloaded_m",
        ),
        migrations.RemoveField(
            model_name="kceventpartner",
            name="evp_apx_reloaded_w",
        ),
    ]
