# Generated by Django 5.2 on 2025-07-04 12:15

import kcevent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kcevent", "0067_remove_kceventpartner_evp_apx_member_d_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kceventpartner",
            name="evp_doc_contract",
            field=models.FileField(
                blank=True,
                help_text="Contract document between event host and event partner.",
                max_length=255,
                null=True,
                upload_to=kcevent.models.getUploadPathEventPartnerContract,
                verbose_name="Contract",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kceventpartnerrolestatistic",
            unique_together={("role", "gender", "event_partner")},
        ),
    ]
