BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXX XXXXXXXX XXXX XXXX XXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXX XXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XX

  XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XXXXXXX

XXXXXX
XXXXXXXX
  XXXX XXXXX XXX XXXX XXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
    XXXX
  XXXXXX
XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      BBBBB BBBBBBBBBBBBBBB
    XXXXXX
    XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XX XX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXX XXXXXXXXXX XXX
  XXXX XXXXXX XXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXX XX XXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX

XXXXXXX
