BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXXXX XXX XXX XXXXXXXX XXX XXX XXXXXXXXXXXXXXXXX XXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
          BBBBBBBBBB
        BB BBBBBBBBBBBBB
            XX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX
        BBBBB
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
            XXXXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
          XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB