BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX
XXXXXXXXXXXXX XXXXX
XXXXXXXX XXXXXX XXX XXXXXXXXXXX XXX XXXXX XXXXX XXXXXX XXXXXXXX XXX XXXXXXXXX XXX  XXXX
  XXXXX XXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
        XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              
              FFFFFFFFFFFFFFFFFFFFFFFFFFFF
              XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB